apiVersion: apps/v1
kind: Deployment
metadata:
  name: d1
spec:
  template:
    metadata:
      name: pod1
      labels:
        app: web
    spec:
      containers:
      - name: container
        image: nginx
        ports:
        - containerPort: 80
        env:
          - name: Name
            valueFrom:
              secretKeyRef:
                name: s2
                key: Name
  replicas: 4
  selector:
    matchLabels:
      app: web
