apiVersion: apps/v1
kind: Deployment
metadata:
  name: replicaset1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: container1
          image: preethi1102/web-app:latest
          ports:
            - containerPort: 8080


